#!/bin/bash

# Install packages if they aren't already installed
# pip3 install -r requirements.txt --user
# pip3 install psycopg --user

# Load environment variables
source ./tests/creds/env_vars/test.env.sh

# Run tests
python3 -m tests.pystackql_tests
